import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Layout from './components/Layout'
import TableauViz from './components/TableauViz'

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Tableau Viz Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <TableauViz />
      </Layout>

    </div>
  )
}

export default Home
